# Dockerfile multi-stage
# Stage 1: Build
FROM node:20 AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Stage 2: Test
FROM node:20 AS test

WORKDIR /app

COPY --from=build /app /app

RUN npm test

# Stage 3: Production
FROM node:20-alpine AS production

WORKDIR /app

COPY --from=build /app/src src

COPY --from=build /app/package.json .

RUN npm install --production

CMD ["node", "src/app.js"]