services:
  app:
    image: app-base-3
    ports:
      - "3000:3000"
    volumes:
      - uploads-data:/app/uploads
      - logs-data:/app/logs
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=mydb

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 20s
      timeout: 10s
      retries: 3

  backup:
    image: offen/docker-volume-backup:latest
    restart: always
    env_file: ./backup.env
    volumes:
      - uploads-data:/backup/app-backup:ro
      - ./backups:/archive
  backrest:
    image: garethgeorge/backrest:latest
    container_name: backrest
    hostname: backrest
    volumes:
      - ./backrest/data:/data
      - ./backrest/config:/config
      - ./backrest/cache:/cache
      - ./backrest/tmp:/tmp
      - ./backrest/backups:/repos/local
      - uploads-data:/uploads-backup
      - logs-data:/logs-backup
    environment:
      - BACKREST_DATA=/data
      - XDG_CACHE_HOME=/cache
      - BACKREST_CONFIG=/config/config.json
    ports:
      - "9898:9898"

volumes:
  uploads-data:
    name: uploads-data
    driver: local
  logs-data:
    name: logs-data
    driver: local
  pgdata:
    name: pgdata
    driver: local
