services:
  app:
    build: .
    environment:
      APP_ENV: "development"
      DEBUG: "true"
      START_SERVER: "true"
      PORT: 3000
      API_URL: "https://api.dev.example.com"
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    command: ["node", "index.js"]
