version: "3.8"
services:
  app:
    build: .
    env_file:
      - .env
    environment:
      APP_ENV: "base"
      START_SERVER: "true"
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    command: ["node", "index.js"]
