# Etapa de build
FROM node:20 AS build

WORKDIR /app

# Variables de entorno para build
ENV NODE_ENV=development

# Copia primero solo package.json y package-lock.json para aprovechar cache de dependencias
COPY package*.json ./

RUN npm ci

# Ahora sí, copia el resto del código fuente
COPY . .

# Compila y limpia en una sola capa para reducir capas intermedias
RUN npm run build \
    && npm cache clean --force

# Etapa de test
FROM node:20 AS test
WORKDIR /app

# Variables de entorno para tests
ENV NODE_ENV=test \
    PORT=3000 \
    DEBUG_REQUEST=false \
    DEFAULT_USER=admin \
    DEFAULT_PASS=12345678 \
    JWT_SECRET=secretKey \
    ENABLE_AUTH=true \
    USE_DB=false \
    DB_HOST=localhost \
    DB_PORT=5432 \
    DB_USER=todo_user \
    DB_PASS=todo_pass \
    DB_NAME=todo_db

COPY --from=build /app /app
RUN npm run test

# Etapa de producción
FROM node:20-alpine AS production

WORKDIR /app

COPY --from=build /app/dist ./dist
COPY --from=build /app/package*.json ./

RUN npm ci --only=production \
    && npm cache clean --force

# Variables de entorno para producción
ENV NODE_ENV=production \
    PORT=3000 \
    DEBUG_REQUEST=false \
    DEFAULT_USER=admin \
    DEFAULT_PASS=12345678 \
    JWT_SECRET=secretKey \
    ENABLE_AUTH=true \
    USE_DB=false \
    DB_HOST=localhost \
    DB_PORT=5432 \
    DB_USER=todo_user \
    DB_PASS=todo_pass \
    DB_NAME=todo_db


EXPOSE $PORT

CMD ["node", "dist/main.js"]