ARG NODE_VERSION=20
ARG PORT=3000
ARG DEBUG_REQUEST=false
ARG ENABLE_AUTH=true
ARG DB_HOST=localhost
ARG DB_PORT=5432
ARG USE_DB=false
ARG DEFAULT_USER=admin
ARG DEFAULT_PASS=12345678
ARG JWT_SECRET=secretKey
ARG DB_USER=todo_user
ARG DB_PASS=todo_pass
ARG DB_NAME=todo_db

# Etapa de build
FROM node:${NODE_VERSION} AS build

WORKDIR /app

# Variables de entorno para build
ENV NODE_ENV=development

# Copia primero solo package.json y package-lock.json para aprovechar cache de dependencias
COPY package*.json ./
RUN npm ci \
    && npm cache clean --force

# Ahora sí, copia el resto del código fuente
COPY . .

# Compila y limpia en una sola capa para reducir capas intermedias
RUN npm run build

# Etapa de test
FROM node:${NODE_VERSION} AS test
WORKDIR /app

ARG PORT
ARG DEBUG_REQUEST
ARG ENABLE_AUTH
ARG DB_HOST
ARG DB_PORT
ARG USE_DB
ARG DEFAULT_USER
ARG DEFAULT_PASS
ARG JWT_SECRET
ARG DB_USER
ARG DB_PASS
ARG DB_NAME

# Variables de entorno para tests
ENV NODE_ENV=test \
    PORT=${PORT} \ 
    DEBUG_REQUEST=${DEBUG_REQUEST} \
    ENABLE_AUTH=${ENABLE_AUTH} \
    DB_HOST=${DB_HOST} \
    DB_PORT=${DB_PORT} \
    USE_DB=${USE_DB} \
    DEFAULT_USER=admin \
    DEFAULT_PASS=12345678 \
    JWT_SECRET=secretKey \    
    DB_USER=todo_user \
    DB_PASS=todo_pass \
    DB_NAME=todo_db

COPY --from=build /app /app

RUN npm run test

# Etapa de producción
FROM node:${NODE_VERSION}-alpine AS production

WORKDIR /app

COPY --from=build /app/dist ./dist
COPY --from=build /app/package*.json .

# Instala solo dependencias de producción y limpia cache en la misma capa
RUN npm ci --omit=dev \
    && npm cache clean --force


ARG PORT
ARG DEBUG_REQUEST
ARG ENABLE_AUTH
ARG DB_HOST
ARG DB_PORT
ARG USE_DB
ARG DEFAULT_USER
ARG DEFAULT_PASS
ARG JWT_SECRET
ARG DB_USER
ARG DB_PASS
ARG DB_NAME

# Variables de entorno para producción
ENV NODE_ENV=production \
    PORT=${PORT} \
    DEBUG_REQUEST=${DEBUG_REQUEST} \
    ENABLE_AUTH=${ENABLE_AUTH} \
    DB_HOST=${DB_HOST} \
    DB_PORT=${DB_PORT} \
    USE_DB=${USE_DB} \
    DEFAULT_USER=${DEFAULT_USER} \
    DEFAULT_PASS=${DEFAULT_PASS} \
    JWT_SECRET=${JWT_SECRET} \
    DB_USER=${DB_USER} \
    DB_PASS=${DB_PASS} \
    DB_NAME=${DB_NAME}


EXPOSE $PORT

CMD ["node", "dist/main.js"]