FROM node:20

COPY package*.json .
RUN apt-get update && \
    apt-get install -y build-essential && \
    npm install && \
    apt-get purge -y build-essential && \
    rm -rf /var/lib/apt/lists/*
COPY . .
RUN npm run build
CMD ["node", "app.js"]
