x-app-base: &app-base
  build:
    context: ./../../../app
    dockerfile: ../03-volumes/ejemplos/Dockerfile
  ports:
    - "3000:3000"
  image: app-base
  container_name: app-base
  environment:
    NODE_ENV: development
    PORT: 3000

services:
  app-base-1:
    <<: *app-base
    container_name: app-base-1
    volumes:
      - type: bind
        source: ./logs_volume/
        target: /app/logs
