services:
  postgres:
    container_name: postgres
    image: postgres:15
    environment: &db-env
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 20s
      timeout: 10s
      retries: 3
