services:
  base-1:
    image: app-base
    ports:
      - "3000:3000"
    environment: &env
      - PORT=3000
      - LOG_LEVEL=debug

  base-2:
    image: app-base
    ports:
      - "4000:3000"
    environment: *env

  base-3:
    image: app-base
    ports:
      - "5000:3000"
    environment: &env-list
      PORT: 3000
      LOG_LEVEL: debug

  base-4:
    image: app-base
    ports:
      - "6000:3000"
    environment:
      <<: *env-list
      LOG_LEVEL: info

networks:
  default:
    driver: bridge
    name: app-base
