version: '3.8'
services:
  web:
    image: nginx:alpine
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
