services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - 5432:5432

  backend:
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
      - USE_DB=true
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=app_db
