services:
  app-base:
    hostname: app-base
    image: ghcr.io/trynewroads/docker-course-advance:latest
    environment:
      DEBUG_LEVEL: debug
      USE_DB: "true"
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_NAME: postgres
    secrets:
      - db_password
    ports:
      - "3005:3000"
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker

  postgres:
    hostname: postgres
    image: postgres:15
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password

secrets:
  db_password:
    file: ./db_password.txt


networks:
  default:
    driver: overlay
