services:
  app-base:
    image: ghcr.io/trynewroads/docker-course-advance:latest
    environment:
      USE_DB: "true"
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS_FILE: /run/secrets/db_password
      DB_NAME: postgres
    ports:
      - "3003:3000"
    secrets:
      - source: db_password_text
        target: db_password
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
      placement:
        constraints:
          - node.role == worker

  postgres:
    image: postgres:15
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      resources:
        limits:
          cpus: "1.00"
          memory: 1G
        reservations:
          cpus: "0.50"
          memory: 512M
    environment:
      POSTGRES_PASSWORD: /run/secrets/db_password
    secrets:
      - source: db_password_text
        target: db_password

secrets:
  db_password_text:
    external: true

networks:
  default:
    driver: overlay
    name: app-base
