services:
  app-base:
    hostname: app-base
    image: ghcr.io/trynewroads/docker-course-advance:latest
    environment:
      USE_DB: "false"
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: password
      DB_NAME: postgres
    ports:
      - "3001:3000"
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker

  postgres:
    hostname: postgres
    image: postgres:15
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
    environment:
      POSTGRES_PASSWORD: password

networks:
  default:
    driver: overlay
