# Dockerfile Fase 2: Agrupando RUN y limpiando archivos temporales
FROM node:20
WORKDIR /app
COPY . .
RUN apt-get update && \
    apt-get install -y build-essential && \
    npm install && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
RUN npm test
CMD ["node", "app.js"]
