FROM node:20

WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install
# Copy the rest of the application code  

COPY . .

# Set environment variables  
ENV LOG_LEVEL=debug
ENV DB_HOST=localhost
ENV DB_PORT=5432
ENV DB_USER=postgres
ENV DB_PASSWORD=devpassword
ENV DB_NAME=app_db_dev
ENV PORT=3000

EXPOSE $PORT
VOLUME /app

CMD ["npm", "run", "start:watch"]
