FROM node:20-alpine

WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install --omit=dev
# Copy the rest of the application code  

COPY . .

# Set environment variables  
ENV LOG_LEVEL=info
ENV DB_HOST=db-prod
ENV DB_PORT=5432
ENV DB_USER=postgres
ENV DB_PASSWORD=prodpassword
ENV DB_NAME=app_db_prod

RUN apk add --no-cache curl

EXPOSE $PORT

CMD ["node", "app.js"]
