name: Exportar slides Marp a PDF

on:
  push:
    paths:
      - '**/slides/*.md'
      - '.github/workflows/marp-pdf.yml'
  pull_request:
    paths:
      - '**/slides/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar Node y Marp CLI
        run: |
          npm install -g @marp-team/marp-cli
      - name: Exportar todos los slides a PDF
        run: |
          find . -type f -path '*/slides/*.md' | while read -r file; do
            pdf_file="${file%.md}.pdf"
            marp "$file" --pdf -o "$pdf_file"
          done
      - name: Subir PDFs como artefacto
        uses: actions/upload-artifact@v3
        with:
          name: slides-pdf
          path: '**/slides/*.pdf'
